<?php

declare(strict_types=1);

namespace AndyDefer\PhpPawapay\Tests\Unit\Builders;

use AndyDefer\PhpPawapay\Builders\CreatePaymentPageBuilder;
use AndyDefer\PhpPawapay\Enums\Country;
use AndyDefer\PhpPawapay\Enums\Currency;
use AndyDefer\PhpPawapay\Enums\Language;
use AndyDefer\PhpPawapay\Enums\PawaPayBaseUrl;
use AndyDefer\PhpPawapay\PawapayClient;
use PHPUnit\Framework\TestCase;

final class CreatePaymentPageBuilderTest extends TestCase
{
    private string $apiToken = 'test-token';

    public function test_builder_creates_client_with_default_values(): void
    {
        $builder = CreatePaymentPageBuilder::create($this->apiToken);
        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_base_url(): void
    {
        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withBaseUrl(PawaPayBaseUrl::PRODUCTION);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_phone_number(): void
    {
        $phoneNumber = '243812345678';

        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withPhoneNumber($phoneNumber);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_amount_as_float(): void
    {
        $amount = 25.50;

        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withAmount($amount);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_currency(): void
    {
        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withCurrency(Currency::USD);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_return_url(): void
    {
        $returnUrl = 'https://example.com/success';

        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withReturnUrl($returnUrl);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_language(): void
    {
        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withLanguage(Language::FR);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_country(): void
    {
        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withCountry(Country::COD);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_customer_message(): void
    {
        $message = 'Test message';

        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withCustomerMessage($message);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_reason(): void
    {
        $reason = 'Test reason';

        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withReason($reason);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_metadata(): void
    {
        $metadata = [
            'orderId' => 'ORD-123456789',
            'customerId' => 'customer@email.com',
        ];

        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withMetadata($metadata);

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_with_metadata_key(): void
    {
        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withMetadataKey('orderId', 'ORD-123456789')
            ->withMetadataKey('customerId', 'customer@email.com');

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }

    public function test_builder_create_returns_new_instance(): void
    {
        $builder1 = CreatePaymentPageBuilder::create($this->apiToken);
        $builder2 = CreatePaymentPageBuilder::create($this->apiToken);

        $this->assertNotSame($builder1, $builder2);
    }

    public function test_builder_chaining_all_methods(): void
    {
        $builder = CreatePaymentPageBuilder::create($this->apiToken)
            ->withBaseUrl(PawaPayBaseUrl::PRODUCTION)
            ->withAutoGeneratedDepositId()
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->withCurrency(Currency::USD)
            ->withReturnUrl('https://example.com/success')
            ->withLanguage(Language::FR)
            ->withCountry(Country::COD)
            ->withCustomerMessage('Test message')
            ->withReason('Test reason')
            ->withMetadataKey('orderId', 'ORD-123456789')
            ->withMetadataKey('customerId', 'customer@email.com');

        $client = $builder->build();

        $this->assertInstanceOf(PawapayClient::class, $client);
    }
}
