<?php

declare(strict_types=1);

namespace AndyDefer\PhpPawapay\Tests\Unit\Builders;

use AndyDefer\PhpPawapay\Builders\InitiateDepositBuilder;
use AndyDefer\PhpPawapay\Enums\Currency;
use AndyDefer\PhpPawapay\Enums\PayerType;
use AndyDefer\PhpPawapay\Enums\Provider;
use AndyDefer\PhpPawapay\ValueObjects\InitiateDepositVO;
use PHPUnit\Framework\TestCase;
use Ramsey\Uuid\Uuid;

final class InitiateDepositBuilderTest extends TestCase
{
    public function test_builder_creates_deposit_with_rdc_usd(): void
    {
        $deposit = InitiateDepositBuilder::create()
            ->withPhoneNumber('243812345678')
            ->withProvider(Provider::VODACOM_MPESA_COD)
            ->withAmount(25.50)
            ->withCurrency(Currency::USD)
            ->build();

        $this->assertInstanceOf(InitiateDepositVO::class, $deposit);
        $this->assertSame('243812345678', $deposit->payer->accountDetails->phoneNumber->getValue());
        $this->assertSame('25.5', $deposit->amount->getValue());
        $this->assertSame(Currency::USD, $deposit->currency);
        $this->assertSame(Provider::VODACOM_MPESA_COD, $deposit->payer->accountDetails->provider);
        $this->assertSame(PayerType::MMO, $deposit->payer->type);
    }

    public function test_builder_creates_deposit_with_required_fields(): void
    {
        $deposit = InitiateDepositBuilder::create()
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->build();

        $this->assertInstanceOf(InitiateDepositVO::class, $deposit);
        $this->assertSame('243812345678', $deposit->payer->accountDetails->phoneNumber->getValue());
        $this->assertSame('25.5', $deposit->amount->getValue());
        $this->assertSame(Currency::ZMW, $deposit->currency);
        $this->assertSame(Provider::MTN_MOMO_ZMB, $deposit->payer->accountDetails->provider);
        $this->assertSame(PayerType::MMO, $deposit->payer->type);
    }

    public function test_builder_with_auto_generated_deposit_id(): void
    {
        $deposit = InitiateDepositBuilder::create()
            ->withAutoGeneratedDepositId()
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->build();

        $this->assertInstanceOf(InitiateDepositVO::class, $deposit);
        $this->assertTrue(Uuid::isValid($deposit->depositId->getValue()));
    }

    public function test_builder_with_custom_deposit_id(): void
    {
        $customId = 'f4401bd2-1568-4140-bf2d-eb77d2b2b639';

        $deposit = InitiateDepositBuilder::create()
            ->withDepositId($customId)
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->build();

        $this->assertSame($customId, $deposit->depositId->getValue());
    }

    public function test_builder_with_provider(): void
    {
        $deposit = InitiateDepositBuilder::create()
            ->withProvider(Provider::VODACOM_MPESA_COD)
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->build();

        $this->assertSame(Provider::VODACOM_MPESA_COD, $deposit->payer->accountDetails->provider);
    }

    public function test_builder_with_currency(): void
    {
        $deposit = InitiateDepositBuilder::create()
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->withCurrency(Currency::USD)
            ->build();

        $this->assertSame(Currency::USD, $deposit->currency);
    }

    public function test_builder_with_client_reference_id(): void
    {
        $deposit = InitiateDepositBuilder::create()
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->withClientReferenceId('REF-RDC-123456')
            ->build();

        $this->assertSame('REF-RDC-123456', $deposit->clientReferenceId->getValue());
    }

    public function test_builder_with_customer_message(): void
    {
        $message = 'Payment for order #RDC-123456';

        $deposit = InitiateDepositBuilder::create()
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->withCustomerMessage($message)
            ->build();

        $this->assertSame('payment for order rdc', $deposit->customerMessage->getValue());
    }

    public function test_builder_with_metadata(): void
    {
        $metadata = [
            'orderId' => 'ORD-RDC-123456789',
            'customerId' => 'customer@email.com',
        ];

        $deposit = InitiateDepositBuilder::create()
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->withMetadata($metadata)
            ->build();

        $this->assertNotNull($deposit->metadata);
        $this->assertSame('ORD-RDC-123456789', $deposit->metadata->get('orderId'));
        $this->assertSame('customer@email.com', $deposit->metadata->get('customerId'));
    }

    public function test_builder_with_metadata_key(): void
    {
        $deposit = InitiateDepositBuilder::create()
            ->withPhoneNumber('243812345678')
            ->withAmount(25.50)
            ->withMetadataKey('orderId', 'ORD-RDC-123456789')
            ->withMetadataKey('customerId', 'customer@email.com')
            ->build();

        $this->assertNotNull($deposit->metadata);
        $this->assertSame('ORD-RDC-123456789', $deposit->metadata->get('orderId'));
        $this->assertSame('customer@email.com', $deposit->metadata->get('customerId'));
    }

    public function test_builder_chaining_all_methods(): void
    {
        $deposit = InitiateDepositBuilder::create()
            ->withDepositId('f4401bd2-1568-4140-bf2d-eb77d2b2b639')
            ->withPhoneNumber('243812345678')
            ->withProvider(Provider::VODACOM_MPESA_COD)
            ->withAmount(25.50)
            ->withCurrency(Currency::USD)
            ->withClientReferenceId('REF-RDC-123456')
            ->withCustomerMessage('Payment for order #RDC-123456')
            ->withMetadataKey('orderId', 'ORD-RDC-123456789')
            ->withMetadataKey('customerId', 'customer@email.com')
            ->build();

        $this->assertSame('f4401bd2-1568-4140-bf2d-eb77d2b2b639', $deposit->depositId->getValue());
        $this->assertSame(PayerType::MMO, $deposit->payer->type);
        $this->assertSame('243812345678', $deposit->payer->accountDetails->phoneNumber->getValue());
        $this->assertSame(Provider::VODACOM_MPESA_COD, $deposit->payer->accountDetails->provider);
        $this->assertSame('25.5', $deposit->amount->getValue());
        $this->assertSame(Currency::USD, $deposit->currency);
        $this->assertSame('REF-RDC-123456', $deposit->clientReferenceId->getValue());
        $this->assertSame('payment for order rdc', $deposit->customerMessage->getValue());
        $this->assertSame('ORD-RDC-123456789', $deposit->metadata->get('orderId'));
        $this->assertSame('customer@email.com', $deposit->metadata->get('customerId'));
    }
}
