<?php

declare(strict_types=1);

namespace AndyDefer\PhpPawapay\Enums;

enum FailureCode: string
{
    // --- Erreurs techniques ---
    case NO_AUTHENTICATION = 'NO_AUTHENTICATION';
    case AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
    case AUTHORISATION_ERROR = 'AUTHORISATION_ERROR';
    case HTTP_SIGNATURE_ERROR = 'HTTP_SIGNATURE_ERROR';
    case INVALID_INPUT = 'INVALID_INPUT';
    case MISSING_PARAMETER = 'MISSING_PARAMETER';
    case UNSUPPORTED_PARAMETER = 'UNSUPPORTED_PARAMETER';
    case INVALID_PARAMETER = 'INVALID_PARAMETER';
    case AMOUNT_OUT_OF_BOUNDS = 'AMOUNT_OUT_OF_BOUNDS';
    case INVALID_AMOUNT = 'INVALID_AMOUNT';
    case INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';
    case INVALID_CURRENCY = 'INVALID_CURRENCY';
    case INVALID_PROVIDER = 'INVALID_PROVIDER';
    case DUPLICATE_METADATA_FIELD = 'DUPLICATE_METADATA_FIELD';
    case DEPOSITS_NOT_ALLOWED = 'DEPOSITS_NOT_ALLOWED';
    case PAYOUTS_NOT_ALLOWED = 'PAYOUTS_NOT_ALLOWED';
    case REFUNDS_NOT_ALLOWED = 'REFUNDS_NOT_ALLOWED';
    case PROVIDER_TEMPORARILY_UNAVAILABLE = 'PROVIDER_TEMPORARILY_UNAVAILABLE';

    // --- Échecs de transaction ---
    case PAYMENT_NOT_APPROVED = 'PAYMENT_NOT_APPROVED';
    case INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE';
    case PAYMENT_IN_PROGRESS = 'PAYMENT_IN_PROGRESS';
    case PAYER_NOT_FOUND = 'PAYER_NOT_FOUND';
    case RECIPIENT_NOT_FOUND = 'RECIPIENT_NOT_FOUND';
    case MANUALLY_CANCELLED = 'MANUALLY_CANCELLED';
    case PAWAPAY_WALLET_OUT_OF_FUNDS = 'PAWAPAY_WALLET_OUT_OF_FUNDS';
    case DEPOSIT_ALREADY_REFUNDED = 'DEPOSIT_ALREADY_REFUNDED';
    case AMOUNT_TOO_LARGE = 'AMOUNT_TOO_LARGE';
    case REFUND_IN_PROGRESS = 'REFUND_IN_PROGRESS';
    case WALLET_LIMIT_REACHED = 'WALLET_LIMIT_REACHED';
    case UNSPECIFIED_FAILURE = 'UNSPECIFIED_FAILURE';
    case UNKNOWN_ERROR = 'UNKNOWN_ERROR';
}
