<?php

declare(strict_types=1);

require './vendor/autoload.php';

use AndyDefer\DomainStructures\Utils\StrictDataObject;
use AndyDefer\PhpClient\ValueObjects\UrlVO;
use AndyDefer\PhpPawapay\Builders\CreatePaymentPageBuilder;
use AndyDefer\PhpPawapay\Enums\Country;
use AndyDefer\PhpPawapay\Enums\Currency;
use AndyDefer\PhpPawapay\Enums\Language;
use AndyDefer\PhpPawapay\Enums\PawaPayBaseUrl;
use AndyDefer\PhpPawapay\Graphs\AmountDetailsGraph;
use AndyDefer\PhpPawapay\PawapayClient;
use AndyDefer\PhpPawapay\Structures\PaymentPageStruct;
use AndyDefer\PhpPawapay\ValueObjects\AmountVO;
use AndyDefer\PhpPawapay\ValueObjects\MessageVO;
use AndyDefer\PhpPawapay\ValueObjects\MetadataVO;
use AndyDefer\PhpPawapay\ValueObjects\PhoneNumberVO;
use AndyDefer\PhpPawapay\ValueObjects\UuidVO;

echo "=== Create Payment Page - Exemples ===\n\n";

// ============================================================
// CAS 1 : Avec le Builder (recommandé)
// ============================================================
echo "1. Avec le Builder (recommandé):\n";

$response = CreatePaymentPageBuilder::create(
    apiToken: 'eyJraWQiOiIxIiwiYWxnIjoiRVMyNTYifQ.eyJ0dCI6IkFBVCIsInN1YiI6Ijk4ODgiLCJtYXYiOiIxIiwiZXhwIjoyMDkwNTk2NDg3LCJpYXQiOjE3NzQ5NzcyODcsInBtIjoiREFGLFBBRiIsImp0aSI6ImUxOGNiNzE5LTAyMWUtNDVkYy05MzQwLTRhODg4YWRmY2QwMSJ9.LhD46ze3F_8lxpb9caaLcRTyH5zEpD5xvbCoxneTIq2FALWDu8nWmZPr3YuRNqDz3q4irjHM60ooR3-JTzI8Cg'
)
    ->withBaseUrl(PawaPayBaseUrl::SANDBOX)
    ->withAutoGeneratedDepositId()
    ->withPhoneNumber('243827833329')
    ->withAmount(24.60)
    ->withCurrency(Currency::USD)
    ->withReturnUrl('http://127.0.0.1:8000/payments/pawapay/success')
    ->withLanguage(Language::FR)
    ->withCountry(Country::COD)
    ->withCustomerMessage('paiement')
    ->withReason('paiement')
    ->withMetadataKey('orderId', 'ORD-123456789')
    ->withMetadataKey('customerId', 'customer@email.com')
    ->execute();

if ($response->isSuccess()) {
    $redirectUrl = $response->getRedirectUrl();
    echo "✅ Page de paiement créée !\n";
    echo 'Redirect URL: '.($redirectUrl ? $redirectUrl->getValue() : 'N/A')."\n\n";
} else {
    echo "❌ Échec de la création de la page de paiement\n";
    if ($response->hasFailureReason()) {
        $failure = $response->getFailureReason();
        echo "Code d'erreur: ".$failure->failureCode."\n";
        echo 'Message: '.$failure->failureMessage."\n\n";
    }
}

// ============================================================
// CAS 2 : Avec le client manuel (sans builder)
// ============================================================
echo "2. Avec le client manuel (sans builder):\n";

$client = new PawapayClient(
    apiToken: 'eyJraWQiOiIxIiwiYWxnIjoiRVMyNTYifQ.eyJ0dCI6IkFBVCIsInN1YiI6Ijk4ODgiLCJtYXYiOiIxIiwiZXhwIjoyMDkwNTk2NDg3LCJpYXQiOjE3NzQ5NzcyODcsInBtIjoiREFGLFBBRiIsImp0aSI6ImUxOGNiNzE5LTAyMWUtNDVkYy05MzQwLTRhODg4YWRmY2QwMSJ9.LhD46ze3F_8lxpb9caaLcRTyH5zEpD5xvbCoxneTIq2FALWDu8nWmZPr3YuRNqDz3q4irjHM60ooR3-JTzI8Cg',
    baseUrl: PawaPayBaseUrl::SANDBOX
);

$depositId = new UuidVO('f1e6cf9f-e492-4d15-b095-3ef49375a43f');
$phoneNumber = new PhoneNumberVO('243827833329');
$amount = new AmountVO(24.60);
$returnUrl = new UrlVO('http://127.0.0.1:8000/payments/pawapay/success');

$amountDetails = new AmountDetailsGraph(
    amount: $amount,
    currency: Currency::USD
);

$metadata = new MetadataVO(
    new StrictDataObject([
        'orderId' => 'ORD-123456789',
        'customerId' => 'customer@email.com',
    ])
);

$paymentPage = new PaymentPageStruct(
    depositId: $depositId,
    returnUrl: $returnUrl,
    amountDetails: $amountDetails,
    phoneNumber: $phoneNumber,
    language: Language::FR,
    country: Country::COD,
    customerMessage: new MessageVO('paiement'),
    reason: new MessageVO('paiement'),
    metadata: $metadata
);

$response = $client->createPaymentPage($paymentPage);

if ($response->isSuccess()) {
    $redirectUrl = $response->getRedirectUrl();
    echo "✅ Page de paiement créée !\n";
    echo 'Redirect URL: '.($redirectUrl ? $redirectUrl->getValue() : 'N/A')."\n";
} else {
    echo "❌ Échec\n";
    if ($response->hasFailureReason()) {
        $failure = $response->getFailureReason();
        echo 'Code: '.$failure->failureCode."\n";
        echo 'Message: '.$failure->failureMessage."\n";
    }
}
