<?php

declare(strict_types=1);

require './vendor/autoload.php';

use AndyDefer\DomainStructures\Utils\StrictDataObject;
use AndyDefer\PhpPawapay\Builders\InitiateDepositBuilder;
use AndyDefer\PhpPawapay\Enums\Currency;
use AndyDefer\PhpPawapay\Enums\PawaPayBaseUrl;
use AndyDefer\PhpPawapay\Enums\PayerType;
use AndyDefer\PhpPawapay\Enums\Provider;
use AndyDefer\PhpPawapay\PawapayClient;
use AndyDefer\PhpPawapay\ValueObjects\AccountDetailsVO;
use AndyDefer\PhpPawapay\ValueObjects\AmountVO;
use AndyDefer\PhpPawapay\ValueObjects\InitiateDepositVO;
use AndyDefer\PhpPawapay\ValueObjects\MessageVO;
use AndyDefer\PhpPawapay\ValueObjects\MetadataVO;
use AndyDefer\PhpPawapay\ValueObjects\PayerVO;
use AndyDefer\PhpPawapay\ValueObjects\PhoneNumberVO;
use AndyDefer\PhpPawapay\ValueObjects\ReferenceVO;
use AndyDefer\PhpPawapay\ValueObjects\UuidVO;

// 1. Créer le client
$client = new PawapayClient(
    apiToken: 'eyJraWQiOiIxIiwiYWxnIjoiRVMyNTYifQ.eyJ0dCI6IkFBVCIsInN1YiI6Ijk4ODgiLCJtYXYiOiIxIiwiZXhwIjoyMDkwNTk2NDg3LCJpYXQiOjE3NzQ5NzcyODcsInBtIjoiREFGLFBBRiIsImp0aSI6ImUxOGNiNzE5LTAyMWUtNDVkYy05MzQwLTRhODg4YWRmY2QwMSJ9.LhD46ze3F_8lxpb9caaLcRTyH5zEpD5xvbCoxneTIq2FALWDu8nWmZPr3YuRNqDz3q4irjHM60ooR3-JTzI8Cg',
    baseUrl: PawaPayBaseUrl::SANDBOX
);

echo "=== Initiate Deposit - Exemples ===\n\n";

// ============================================================
// EXEMPLE 1 : Avec le Builder (recommandé) - RDC (USD)
// ============================================================
echo "1. Avec le Builder (recommandé) - RDC (USD):\n";

$deposit = InitiateDepositBuilder::create()
    ->withAutoGeneratedDepositId()
    ->withPhoneNumber('243812345678') // RDC (Code pays +243)
    ->withProvider(Provider::VODACOM_MPESA_COD) // Vodacom MPESA RDC
    ->withAmount(25.50)
    ->withCurrency(Currency::USD)
    ->withClientReferenceId('INV-RDC-123456')
    ->withCustomerMessage('Payment for order #RDC-123456')
    ->withMetadataKey('orderId', 'ORD-RDC-123456789')
    ->withMetadataKey('customerId', 'customer@email.com')
    ->build();

$response = $client->initiateDeposit($deposit);

if ($response->isSuccess()) {
    if ($response->isAccepted()) {
        echo "✅ Dépôt accepté !\n";
        echo 'ID: '.$response->getDepositId()."\n";
        echo 'Statut: '.$response->getStatus()->value."\n";
        echo 'Créé: '.$response->getCreated()."\n\n";
    } elseif ($response->isDuplicateIgnored()) {
        echo "⚠️ Dépôt dupliqué ignoré\n";
        echo 'ID: '.$response->getDepositId()."\n\n";
    }
} else {
    echo "❌ Échec du dépôt\n";
    echo 'Statut: '.$response->getStatus()->value."\n";
    if ($response->hasFailureReason()) {
        $failure = $response->getFailureReason();
        echo "Code d'erreur: ".$failure->failureCode."\n";
        echo 'Message: '.$failure->failureMessage."\n\n";
    }
}

// ============================================================
// EXEMPLE 2 : Sans builder (manuel) - RDC (USD)
// ============================================================
echo "2. Sans builder (manuel) - RDC (USD):\n";

$depositId = new UuidVO;
$phoneNumber = new PhoneNumberVO('243812345678'); // RDC
$amount = new AmountVO(25.50);

$accountDetails = new AccountDetailsVO(
    phoneNumber: $phoneNumber,
    provider: Provider::VODACOM_MPESA_COD // Vodacom MPESA RDC
);

$payer = new PayerVO(
    type: PayerType::MMO,
    accountDetails: $accountDetails
);

$metadata = new MetadataVO(
    new StrictDataObject([
        'orderId' => 'ORD-RDC-123456789',
        'customerId' => 'customer@email.com',
        'isPII' => true,
    ])
);

$deposit = new InitiateDepositVO(
    depositId: $depositId,
    payer: $payer,
    amount: $amount,
    currency: Currency::USD,
    preAuthorisationCode: null,
    clientReferenceId: new ReferenceVO('INV-RDC-123456'),
    customerMessage: new MessageVO('Payment for order #RDC-123456'),
    metadata: $metadata
);

$response = $client->initiateDeposit($deposit);

if ($response->isSuccess()) {
    if ($response->isAccepted()) {
        echo "✅ Dépôt accepté !\n";
        echo 'ID: '.$response->getDepositId()."\n";
        echo 'Statut: '.$response->getStatus()->value."\n";
        echo 'Créé: '.$response->getCreated()."\n";
    } elseif ($response->isDuplicateIgnored()) {
        echo "⚠️ Dépôt dupliqué ignoré\n";
        echo 'ID: '.$response->getDepositId()."\n";
    }
} else {
    echo "❌ Échec du dépôt\n";
    echo 'Statut: '.$response->getStatus()->value."\n";
    if ($response->hasFailureReason()) {
        $failure = $response->getFailureReason();
        echo "Code d'erreur: ".$failure->failureCode."\n";
        echo 'Message: '.$failure->failureMessage."\n";
    }
}
