<?php

declare(strict_types=1);

namespace AndyDefer\PhpPawapay\Builders;

use AndyDefer\DomainStructures\Utils\StrictDataObject;
use AndyDefer\PhpClient\ValueObjects\UrlVO;
use AndyDefer\PhpPawapay\Enums\Country;
use AndyDefer\PhpPawapay\Enums\Currency;
use AndyDefer\PhpPawapay\Enums\Language;
use AndyDefer\PhpPawapay\Enums\PawaPayBaseUrl;
use AndyDefer\PhpPawapay\Graphs\AmountDetailsGraph;
use AndyDefer\PhpPawapay\PawapayClient;
use AndyDefer\PhpPawapay\Responses\CreatePaymentPageResponse;
use AndyDefer\PhpPawapay\Structures\PaymentPageStruct;
use AndyDefer\PhpPawapay\ValueObjects\AmountVO;
use AndyDefer\PhpPawapay\ValueObjects\MessageVO;
use AndyDefer\PhpPawapay\ValueObjects\MetadataVO;
use AndyDefer\PhpPawapay\ValueObjects\PhoneNumberVO;
use AndyDefer\PhpPawapay\ValueObjects\UuidVO;
use Ramsey\Uuid\Uuid;

final class CreatePaymentPageBuilder
{
    private string $apiToken;

    private PawaPayBaseUrl $baseUrl;

    private UuidVO $depositId;

    private PhoneNumberVO $phoneNumber;

    private AmountVO $amount;

    private Currency $currency;

    private UrlVO $returnUrl;

    private Language $language;

    private Country $country;

    private ?MessageVO $customerMessage = null;

    private ?MessageVO $reason = null;

    private ?MetadataVO $metadata = null;

    public function __construct(string $apiToken)
    {
        $this->apiToken = $apiToken;
        $this->baseUrl = PawaPayBaseUrl::SANDBOX;
        $this->depositId = new UuidVO(Uuid::uuid4()->toString());
        $this->language = Language::EN;
        $this->country = Country::ZMB;
        $this->currency = Currency::ZMW;
    }

    public function withBaseUrl(PawaPayBaseUrl $baseUrl): self
    {
        $this->baseUrl = $baseUrl;

        return $this;
    }

    public function withDepositId(string $depositId): self
    {
        $this->depositId = new UuidVO($depositId);

        return $this;
    }

    public function withAutoGeneratedDepositId(): self
    {
        $this->depositId = new UuidVO(Uuid::uuid4()->toString());

        return $this;
    }

    public function withPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = new PhoneNumberVO($phoneNumber);

        return $this;
    }

    public function withAmount(AmountVO|float $amount): self
    {
        $this->amount = AmountVO::from($amount);

        return $this;
    }

    public function withCurrency(Currency $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function withReturnUrl(string $returnUrl): self
    {
        $this->returnUrl = new UrlVO($returnUrl);

        return $this;
    }

    public function withLanguage(Language $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function withCountry(Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function withCustomerMessage(?string $message): self
    {
        $this->customerMessage = $message !== null ? new MessageVO($message) : null;

        return $this;
    }

    public function withReason(?string $reason): self
    {
        $this->reason = $reason !== null ? new MessageVO($reason) : null;

        return $this;
    }

    public function withMetadata(array $metadata): self
    {
        $this->metadata = new MetadataVO(new StrictDataObject($metadata));

        return $this;
    }

    public function withMetadataKey(string $key, string $value): self
    {
        $data = $this->metadata !== null ? $this->metadata->toArray() : [];
        $data[$key] = $value;
        $this->metadata = new MetadataVO(new StrictDataObject($data));

        return $this;
    }

    public function build(): PawapayClient
    {
        return new PawapayClient(
            apiToken: $this->apiToken,
            baseUrl: $this->baseUrl
        );
    }

    public function execute(): CreatePaymentPageResponse
    {
        $client = $this->build();

        $amountDetails = new AmountDetailsGraph(
            amount: $this->amount,
            currency: $this->currency
        );

        $paymentPage = new PaymentPageStruct(
            depositId: $this->depositId,
            returnUrl: $this->returnUrl,
            amountDetails: $amountDetails,
            phoneNumber: $this->phoneNumber,
            language: $this->language,
            country: $this->country,
            customerMessage: $this->customerMessage,
            reason: $this->reason,
            metadata: $this->metadata
        );

        return $client->createPaymentPage($paymentPage);
    }

    public static function create(string $apiToken): self
    {
        return new self($apiToken);
    }
}
