<?php

declare(strict_types=1);

namespace AndyDefer\PhpPawapay\Builders;

use AndyDefer\DomainStructures\Utils\StrictDataObject;
use AndyDefer\PhpPawapay\Enums\Currency;
use AndyDefer\PhpPawapay\Enums\PayerType;
use AndyDefer\PhpPawapay\Enums\Provider;
use AndyDefer\PhpPawapay\ValueObjects\AccountDetailsVO;
use AndyDefer\PhpPawapay\ValueObjects\AmountVO;
use AndyDefer\PhpPawapay\ValueObjects\InitiateDepositVO;
use AndyDefer\PhpPawapay\ValueObjects\MessageVO;
use AndyDefer\PhpPawapay\ValueObjects\MetadataVO;
use AndyDefer\PhpPawapay\ValueObjects\PayerVO;
use AndyDefer\PhpPawapay\ValueObjects\PhoneNumberVO;
use AndyDefer\PhpPawapay\ValueObjects\PreAuthorisationCodeVO;
use AndyDefer\PhpPawapay\ValueObjects\ReferenceVO;
use AndyDefer\PhpPawapay\ValueObjects\UuidVO;
use Ramsey\Uuid\Uuid;

final class InitiateDepositBuilder
{
    private UuidVO $depositId;

    private PayerType $payerType;

    private PhoneNumberVO $phoneNumber;

    private Provider $provider;

    private AmountVO $amount;

    private Currency $currency;

    private ?string $preAuthorisationCode = null;

    private ?string $clientReferenceId = null;

    private ?string $customerMessage = null;

    private ?MetadataVO $metadata = null;

    public function __construct()
    {
        $this->depositId = new UuidVO(Uuid::uuid4()->toString());
        $this->payerType = PayerType::MMO;
        $this->provider = Provider::MTN_MOMO_ZMB;
        $this->currency = Currency::ZMW;
    }

    public function withDepositId(string $depositId): self
    {
        $this->depositId = new UuidVO($depositId);

        return $this;
    }

    public function withAutoGeneratedDepositId(): self
    {
        $this->depositId = new UuidVO(Uuid::uuid4()->toString());

        return $this;
    }

    public function withPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = new PhoneNumberVO($phoneNumber);

        return $this;
    }

    public function withProvider(Provider $provider): self
    {
        $this->provider = $provider;

        return $this;
    }

    public function withAmount(float $amount): self
    {
        $this->amount = new AmountVO($amount);

        return $this;
    }

    public function withCurrency(Currency $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function withPreAuthorisationCode(?string $code): self
    {
        $this->preAuthorisationCode = $code;

        return $this;
    }

    public function withClientReferenceId(?string $referenceId): self
    {
        $this->clientReferenceId = $referenceId;

        return $this;
    }

    public function withCustomerMessage(?string $message): self
    {
        $this->customerMessage = $message;

        return $this;
    }

    public function withMetadata(array $metadata): self
    {
        $this->metadata = new MetadataVO(new StrictDataObject($metadata));

        return $this;
    }

    public function withMetadataKey(string $key, string $value): self
    {
        $data = $this->metadata !== null ? $this->metadata->toArray() : [];
        $data[$key] = $value;
        $this->metadata = new MetadataVO(new StrictDataObject($data));

        return $this;
    }

    public function build(): InitiateDepositVO
    {
        $accountDetails = new AccountDetailsVO(
            phoneNumber: $this->phoneNumber,
            provider: $this->provider,
        );

        $payer = new PayerVO(
            type: $this->payerType,
            accountDetails: $accountDetails,
        );

        return new InitiateDepositVO(
            depositId: $this->depositId,
            payer: $payer,
            amount: $this->amount,
            currency: $this->currency,
            preAuthorisationCode: $this->preAuthorisationCode !== null
                ? PreAuthorisationCodeVO::from($this->preAuthorisationCode)
                : null,
            clientReferenceId: $this->clientReferenceId !== null
                ? ReferenceVO::from($this->clientReferenceId)
                : null,
            customerMessage: $this->customerMessage !== null
                ? MessageVO::from($this->customerMessage)
                : null,
            metadata: $this->metadata,
        );
    }

    public static function create(): self
    {
        return new self;
    }
}
